name: sapt-preproc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.4.6
  - scipy=1.17.1
  - pyscf=2.14.0
  - openmm=8.6.0
  - pdbfixer=1.12
  - gemmi=0.7.4
  - rdkit=2026.03.5
  - pytest=8.4.2
  - pip
  - jupyter
  - ipykernel
